### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by sudazzk** [XpastaX/ConFEDE#1]
请问一下，pytorch_metric_learning 这个包是哪个版本的？

**Comment by AZYoung233** [comment]
同问，在计算损失的时候会提示这个包报错了，但是找不到源头

**Comment by chenfagao-1** [comment]
> 同问，在计算损失的时候会提示这个包报错了，但是找不到源头

你好你们跑通了吗，有解决这些问题吗

**Comment by chenfagao-1** [comment]
> 请问一下，pytorch_metric_learning 这个包是哪个版本的？
你好请问这个需要运行哪个文件才能跑起来吗

**Comment by sudazzk** [comment]
我也没跑起来，没继续尝试

**Comment by AZYoung233** [comment]
我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时

**Comment by chenfagao-1** [comment]
> 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时

兄弟你用什么指令跑起来的吗，我用python config.py除了新建几个文件夹啥反应都没有

**Comment by chenfagao-1** [comment]
> 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
  File "main-fusion.py", line 23, in <module>
    TVA_train_fusion('TVA_fusion', check=check,
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 59, in TVA_train_fusion
    train_data = MOSIDataloader('train', batch_size=batch_size, use_similarity=True, simi_return_mono=False,
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 214, in MOSIDataloader
    dataset = MOSIDataset(name, use_similarity=use_similarity, simi_return_mono=simi_return_mono)
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 14, in __init__
    self.data = pk.load(f)[type]
_pickle.UnpicklingError: invalid load key, '\x00'.你跑的时候有遇到这个问题吗

**Comment by AZYoung233** [comment]
> > 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
> > File "main-fusion.py", line 23, in 
> > TVA_train_fusion('TVA_fusion', check=check,
> > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 59, in TVA_train_fusion
> > train_data = MOSIDataloader('train', batch_size=batch_size, use_similarity=True, simi_return_mono=False,
> > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 214, in MOSIDataloader
> > dataset = MOSIDataset(name, use_similarity=use_similarity, simi_return_mono=simi_return_mono)
> > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 14, in **init**
> > self.data = pk.load(f)[type]
> > _pickle.UnpicklingError: invalid load key, '\x00'.你跑的时候有遇到这个问题吗

你做预训练了吗？

**Comment by chenfagao-1** [comment]
> > > 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
> > > File "main-fusion.py", line 23, in
> > > TVA_train_fusion('TVA_fusion', check=check,
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 59, in TVA_train_fusion
> > > train_data = MOSIDataloader('train', batch_size=batch_size, use_similarity=True, simi_return_mono=False,
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 214, in MOSIDataloader
> > > dataset = MOSIDataset(name, use_similarity=use_similarity, simi_return_mono=simi_return_mono)
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 14, in **init**
> > > self.data = pk.load(f)[type]
> > > _pickle.UnpicklingError: invalid load key, '\x00'.你跑的时候有遇到这个问题吗
> 
> 你做预训练了吗？
谢谢这个问题解决了，原来是我那个pkl文件没缺失了，重新下载了一遍可以了

**Comment by chenfagao-1** [comment]
> 同问，在计算损失的时候会提示这个包报错了，但是找不到源头
Traceback (most recent call last):
  File "main-fusion.py", line 23, in <module>
    TVA_train_fusion('TVA_fusion', check=check,
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 109, in TVA_train_fusion
    pred, fea, all_loss, loss, sub_loss = model(sample1, sample2, return_loss=True)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/model/net/constrastive/TVA_fusion.py", line 176, in forward
    sup_const_loss += self.ntxent_loss(torch.cat(pre_sample_x, dim=0), pre_sample_label,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 37, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)
  File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/util/metrics.py", line 59, in compute_loss
    mat = self.distance(embeddings)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'cont_NTXentLoss' object has no attribute 'distance'
我预训练好了跑main-fusion.py的时候出现了这个报错，你有出现过吗 ？

**Comment by chenfagao-1** [comment]
> > > 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
> > > File "main-fusion.py", line 23, in
> > > TVA_train_fusion('TVA_fusion', check=check,
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 59, in TVA_train_fusion
> > > train_data = MOSIDataloader('train', batch_size=batch_size, use_similarity=True, simi_return_mono=False,
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 214, in MOSIDataloader
> > > dataset = MOSIDataset(name, use_similarity=use_similarity, simi_return_mono=simi_return_mono)
> > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 14, in **init**
> > > self.data = pk.load(f)[type]
> > > _pickle.UnpicklingError: invalid load key, '\x00'.你跑的时候有遇到这个问题吗
> 
> 你做预训练了吗？

兄弟你pytorch_metric_learning包

> 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
兄弟你pytorch_metric_learning包具体是哪个版本的吗，我1.0.0以下试了好几个版本都会报错

**Comment by AZYoung233** [comment]
> > > > 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
> > > > File "main-fusion.py", line 23, in
> > > > TVA_train_fusion('TVA_fusion', check=check,
> > > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 59, in TVA_train_fusion
> > > > train_data = MOSIDataloader('train', batch_size=batch_size, use_similarity=True, simi_return_mono=False,
> > > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 214, in MOSIDataloader
> > > > dataset = MOSIDataset(name, use_similarity=use_similarity, simi_return_mono=simi_return_mono)
> > > > File "/root/autodl-tmp/ConFEDE-Graph_Main/MOSI/dataloader/MOSI.py", line 14, in **init**
> > > > self.data = pk.load(f)[type]
> > > > _pickle.UnpicklingError: invalid load key, '\x00'.你跑的时候有遇到这个问题吗
> > 
> > 
> > 你做预训练了吗？
> 
> 兄弟你pytorch_metric_learning包
> 
> > 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时
> > 兄弟你pytorch_metric_learning包具体是哪个版本的吗，我1.0.0以下试了好几个版本都会报错

0.9.99

**Comment by Taylor-HHT** [comment]
@AZYoung233 你好请问你有遇到以下这个问题吗？
Traceback (most recent call last):
  File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/main-fusion.py", line 23, in <module>
    TVA_train_fusion('TVA_fusion', check=check,
  File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 117, in TVA_train_fusion
    result, result_loss = eval(model, metrics, 'valid', device, config)
  File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 152, in eval
    _pred, fea, _all_loss, _loss, _ = model(sample, None, return_loss=True)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/model/net/constrastive/TVA_fusion.py", line 148, in forward
    pred_mono = self.mono_decoder(x_sds)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/model/decoder/classifier.py", line 25, in forward
    x = self.MLP(x)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2304 and 384x192)

**Comment by XpastaX** [comment]
Below are the detailed environment. I am using **pytorch-metric-learning 0.9.99**，with **python3.8.8**
absl-py                 0.12.0            
appdirs                 1.4.4              
astunparse              1.6.3              
audioread               2.1.9              
boto3                   1.17.78            
botocore                1.20.78            
cachetools              4.2.1              
certifi                 2021.5.30          
cffi                    1.14.5            
chardet                 4.0.0              
click                   7.1.2              
cycler                  0.10.0            
Cython                  0.29.28            
decorator               5.0.9              
dill                    0.3.4
editdistance            0.5.3
emoji                   1.2.0
et-xmlfile              1.0.1
faiss                   1.7.0
filelock                3.0.12
flatbuffers             1.12
gast                    0.3.3
gensim                  4.2.0
google-auth             1.28.0
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
grpcio                  1.32.0
h5py                    2.10.0
idna                    2.10
jieba                   0.39
Jinja2                  3.1.2
jmespath                0.10.0
joblib                  1.0.1
Keras-Preprocessing     1.1.2
kiwisolver              1.3.1
librosa                 0.8.0
llvmlite                0.36.0
Markdown                3.3.4
MarkupSafe              2.1.1
matplotlib              3.4.2
mkl-fft                 1.3.0
mkl-random              1.1.1
mkl-service             2.3.0
multiprocess            0.70.12.2
networkx                2.6.3
numba                   0.53.1
numpy                   1.19.5
nvidia-ml-py            11.525.84
oauthlib                3.1.0
openpyxl                3.0.7
opt-einsum              3.3.0
packaging               20.9
pandas                  1.2.4
pathos                  0.2.8
Pillow                  8.2.0
pip                     21.0.1
pooch                   1.3.0
portalocker             2.0.0
pox                     0.3.0
ppft                    1.6.6.4
prettytable             3.7.0
protobuf                3.15.7
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.20
pydub                   0.25.1
pyparsing               2.4.7
pyrouge                 0.1.3
python-dateutil         2.8.1
pytorch-metric-learning 0.9.99
pytorch-pretrained-bert 0.6.2
pytz                    2021.1
pywin32                 300
regex                   2021.4.4
requests                2.25.1
requests-oauthlib       1.3.0
resampy                 0.2.2
rouge                   1.0.0
threadpoolctl           2.1.0
tokenizers              0.10.2
torch                   1.8.1+cu111
torchaudio              0.8.1
torchsummary            1.5.1
torchvision             0.9.1
tqdm                    4.59.0
transformers            4.5.1
typing-extensions       3.7.4.3
ujson                   4.0.2
urllib3                 1.26.4
wcwidth                 0.2.6
Werkzeug                1.0.1
wheel                   0.36.2
wincertstore            0.2
wrapt                   1.12.1
xlrd                    2.0.1

**Comment by Taylor-HHT** [comment]
收到啦，thanks！

**Comment by wuxy07** [comment]
> @AZYoung233 你好请问你有遇到以下这个问题吗？ Traceback (most recent call last): File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/main-fusion.py", line 23, in TVA_train_fusion('TVA_fusion', check=check, File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 117, in TVA_train_fusion result, result_loss = eval(model, metrics, 'valid', device, config) File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/train/constrastive/TVA_fusion_train.py", line 152, in eval _pred, fea, _all_loss, _loss, _ = model(sample, None, return_loss=True) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/model/net/constrastive/TVA_fusion.py", line 148, in forward pred_mono = self.mono_decoder(x_sds) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/xxx/projects/ConFEDE-Graph_Main/MOSI/model/decoder/classifier.py", line 25, in forward x = self.MLP(x) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward input = module(input) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/xxx/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward return F.linear(input, self.weight, self.bias) RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2304 and 384x192)

请问您这个问题解决了吗，我也遇到了这个问题

**Comment by Taylor-HHT** [comment]
收到啦，thanks！

**Comment by laodetangkoushui** [comment]
> 我这边测试是1.0以下的版本应该是可以的，不过结果复现英文上差了1-2个点，中文的除了ACC2和F1，其他指标反而比论文里高。而且在相似度计算的时候特别费时

能否提供给我一份您复现的ckpt文件，非常感谢

**Comment by Taylor-HHT** [comment]
收到啦，thanks！

**Comment by wangyihan1128** [comment]
F:\miniconda3\envs\env310\python.exe "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\main-fusion.py" 
TVA_fusion
---------------TVA_EXP_all---------------
The pytorch-metric-learning testing module requires faiss. You can install the GPU version with the command 'conda install faiss-gpu -c pytorch'
                        or the CPU version with 'conda install faiss-cpu -c pytorch'. Learn more at https://github.com/facebookresearch/faiss/blob/master/INSTALL.md
F:\miniconda3\envs\env310\lib\site-packages\torch\nn\modules\transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
model loaded from:
F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_text_encoder.ckpt
F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_vision_encoder.ckpt
F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_audio_encoder.ckpt
Collecting New embeddings
Updating Similarity Matrix
Epoch:1|All_loss:nan|Loss:nan|SDS_loss:nan: 100%|██████████| 43/43 [00:19<00:00,  2.25it/s]
EVAL valid
F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\_array_api.py:245: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)
Traceback (most recent call last):
  File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\main-fusion.py", line 21, in <module>
    TVA_train_fusion('TVA_fusion', check=check,
  File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\TVA_fusion_train.py", line 119, in TVA_train_fusion
    result, result_loss = eval(model, metrics, 'valid', device, config)
  File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\TVA_fusion_train.py", line 155, in eval
    eval_results = metrics.eval_sims_regression(truth, pred)
  File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\metrics.py", line 255, in eval_sims_regression
    f_score = f1_score(test_truth_a2, test_preds_a2, average='weighted')
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py", line 1238, in f1_score
    return fbeta_score(
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\_param_validation.py", line 184, in wrapper
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py", line 1411, in fbeta_score
    _, _, f, _ = precision_recall_fscore_support(
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\_param_validation.py", line 184, in wrapper
    return func(*args, **kwargs)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py", line 1721, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py", line 1499, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics\_classification.py", line 86, in _check_targets
    type_pred = type_of_target(y_pred, input_name="y_pred")
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\multiclass.py", line 382, in type_of_target
    _assert_all_finite(data, input_name=input_name)
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\validation.py", line 124, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\validation.py", line 173, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input y_pred contains NaN.

Process finished with exit code 1


有没有遇到这个问题的大家？

**Comment by Taylor-HHT** [comment]
收到啦，thanks！

**Comment by pppz2024** [comment]
> F:\miniconda3\envs\env310\python.exe "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\main-fusion.py" TVA_fusion ---------------TVA_EXP_all--------------- The pytorch-metric-learning testing module requires faiss. You can install the GPU version with the command 'conda install faiss-gpu -c pytorch' or the CPU version with 'conda install faiss-cpu -c pytorch'. Learn more at https://github.com/facebookresearch/faiss/blob/master/INSTALL.md F:\miniconda3\envs\env310\lib\site-packages\torch\nn\modules\transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance) warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}") model loaded from: F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_text_encoder.ckpt F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_vision_encoder.ckpt F:/ConFEDE-Graph_Main/ConFEDE-Graph_Main/SIMS/ckpt/fea_encoder/best_MAE_audio_encoder.ckpt Collecting New embeddings Updating Similarity Matrix Epoch:1|All_loss:nan|Loss:nan|SDS_loss:nan: 100%|██████████| 43/43 [00:19<00:00, 2.25it/s] EVAL valid F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils_array_api.py:245: RuntimeWarning: invalid value encountered in cast return x.astype(dtype, copy=copy, casting=casting) Traceback (most recent call last): File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\main-fusion.py", line 21, in TVA_train_fusion('TVA_fusion', check=check, File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\TVA_fusion_train.py", line 119, in TVA_train_fusion result, result_loss = eval(model, metrics, 'valid', device, config) File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\TVA_fusion_train.py", line 155, in eval eval_results = metrics.eval_sims_regression(truth, pred) File "F:\pycharmproject\pythonProject\ConFEDE-Graph_Mainzuixin\SIMS\all code\metrics.py", line 255, in eval_sims_regression f_score = f1_score(test_truth_a2, test_preds_a2, average='weighted') File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils_param_validation.py", line 211, in wrapper return func(*args, **kwargs) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics_classification.py", line 1238, in f1_score return fbeta_score( File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils_param_validation.py", line 184, in wrapper return func(*args, **kwargs) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics_classification.py", line 1411, in fbeta_score _, _, f, _ = precision_recall_fscore_support( File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils_param_validation.py", line 184, in wrapper return func(*args, **kwargs) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics_classification.py", line 1721, in precision_recall_fscore_support labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics_classification.py", line 1499, in _check_set_wise_labels y_type, y_true, y_pred = _check_targets(y_true, y_pred) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\metrics_classification.py", line 86, in _check_targets type_pred = type_of_target(y_pred, input_name="y_pred") File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\multiclass.py", line 382, in type_of_target _assert_all_finite(data, input_name=input_name) File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\validation.py", line 124, in _assert_all_finite _assert_all_finite_element_wise( File "F:\miniconda3\envs\env310\lib\site-packages\sklearn\utils\validation.py", line 173, in _assert_all_finite_element_wise raise ValueError(msg_err) ValueError: Input y_pred contains NaN.
> 
> Process finished with exit code 1
> 
> 有没有遇到这个问题的大家？

请问解决了吗

**Comment by Taylor-HHT** [comment]
收到啦，thanks！
