### ISSUE TITLE
数据采样器

### ISSUE THREAD

**Issue by 2000CLW** [XpastaX/ConFEDE#11]
您好，我想问您一下论文中数据采样器部分的问题：在论文中提到为样本选择相似样本和不相似样本的数据采样器的输入是三个模态通过Encoder提取的初级特征T，V，A，然后计算余弦相似度。但是代码中计算余弦相似度是直接用的SIMS数据集提供的Encoder之前的数据。所以我想问一下到底应该用经过Encoder之前还是之后的数据来计算余弦相似度呢？

**Comment by XpastaX** [comment]
你好。 在训练过程中，trainer会在第一个epoch开始时更新matrix。使用的是encoder提取的特征
https://github.com/XpastaX/ConFEDE/blob/073babb931010cc81256ff0ed569d424da6a2e52/SIMS/train/constrastive/TVA_fusion_train.py#L91
dataloader中自带的初始化使用的是没有经过encoder的原始特征，上传时没有删除。

**Comment by 2000CLW** [comment]
感谢您的回复！您提到的“dataloader中自带的初始化使用的是没有经过encoder的原始特征，上传时没有删除”，我不太理解是没有删除哪部分，因为在您提供的代码中直接对未经过Encoder的数据进行了平均和计算余弦相似度。


1010872305
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XpastaX/ConFEDE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XpastaX/ConFEDE] 数据采样器 (Issue #11)





 
你好。 在训练过程中，trainer会在第一个epoch开始时更新matrix。使用的是encoder提取的特征
 https://github.com/XpastaX/ConFEDE/blob/073babb931010cc81256ff0ed569d424da6a2e52/SIMS/train/constrastive/TVA_fusion_train.py#L91
 dataloader中自带的初始化使用的是没有经过encoder的原始特征，上传时没有删除。
