### ISSUE TITLE
关于config中的encoder_path和model_path

### ISSUE THREAD

**Issue by Korvas-hb** [XpastaX/ConFEDE#12]
您好，我想求一份三个模态的各自训练好的文件。
![image](https://github.com/XpastaX/ConFEDE/assets/66191779/8046cdca-4d77-4661-b039-40871c0792c1)

**Comment by pppz2024** [comment]
你好，没看懂README文件，请问怎样具体去配置和运行代码

**Comment by Korvas-hb** [comment]
> 你好，没看懂README文件，请问怎样具体去配置和运行代码

你好，该文章的closed issue“requirements.txt”里面有对应的下载的包，直接对照安装即可。我运行代码都是直接使用python main-fusion.py  直接进行运行。

**Comment by lxq666666** [comment]
你好，这个requirements.txt到底在哪，没找到

**Comment by Korvas-hb** [comment]
> 你好，这个requirements.txt到底在哪，没找到

![image](https://github.com/XpastaX/ConFEDE/assets/66191779/fed0736f-e2c4-4714-b9cf-5e4346f21515)
蓝色的箭头指向那个issue里面有，作者在里面有发布的。稍微翻一下能找到

**Comment by XpastaX** [comment]
> 您好，我想求一份三个模态的各自训练好的文件。 ![image](https://private-user-images.githubusercontent.com/66191779/331137562-8046cdca-4d77-4661-b039-40871c0792c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzU5NjYsIm5iZiI6MTcxNjE3NTY2NiwicGF0aCI6Ii82NjE5MTc3OS8zMzExMzc1NjItODA0NmNkY2EtNGQ3Ny00NjYxLWIwMzktNDA4NzFjMDc5MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAzMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDNlNTg2ZjljNGQ0MGJiMmRkY2VmNjg0MzMyMjkyYzRmMDMzZTZiZWM1NjgwZDJiMjNkMDRlOTkyNDcxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D7xzKAkuO8xtdRZdxPylBlEpn5TABN3428P4sti4a9g)

Hi, 我们的服务器清理过一次，目前只留下了最终的模型文件。如果要做项目的话，可以考虑直接加载最终模型，然后使用encoder作为项目使用，经过多模态训练的encoder效果应该会更好。原始的encoder我这边再找一下，看看能不能找到。

**Comment by pppz2024** [comment]
> > 您好，我想求一份三个模态的各自训练好的文件。 ![image](https://private-user-images.githubusercontent.com/66191779/331137562-8046cdca-4d77-4661-b039-40871c0792c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzU5NjYsIm5iZiI6MTcxNjE3NTY2NiwicGF0aCI6Ii82NjE5MTc3OS8zMzExMzc1NjItODA0NmNkY2EtNGQ3Ny00NjYxLWIwMzktNDA4NzFjMDc5MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAzMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDNlNTg2ZjljNGQ0MGJiMmRkY2VmNjg0MzMyMjkyYzRmMDMzZTZiZWM1NjgwZDJiMjNkMDRlOTkyNDcxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D7xzKAkuO8xtdRZdxPylBlEpn5TABN3428P4sti4a9g)
> 
> Hi, 我们的服务器清理过一次，目前只留下了最终的模型文件。如果要做项目的话，可以考虑直接加载最终模型，然后使用encoder作为项目使用，经过多模态训练的encoder效果应该会更好。原始的encoder我这边再找一下，看看能不能找到。

您好 我也相求一份三模态各自训练好的文件

**Comment by xixi193** [comment]
> 您好，我想求一份三个模态的各自训练好的文件。 ![image](https://private-user-images.githubusercontent.com/66191779/331137562-8046cdca-4d77-4661-b039-40871c0792c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTc2OTIsIm5iZiI6MTcyNDY1NzM5MiwicGF0aCI6Ii82NjE5MTc3OS8zMzExMzc1NjItODA0NmNkY2EtNGQ3Ny00NjYxLWIwMzktNDA4NzFjMDc5MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYzliOTI2YzZhOTFjM2E2Y2I1MjE3OWYwNzc3OWI5ZmNmZDZiNWNlMThmYjE0MmIzNGQzMTBhMTIwZGFjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-6P0SJOzSGg1r19d_kOSqDDuSL6AEA88IaVJAXGWr0)

您好，请问这个问题怎么解决呢

**Comment by XpastaX** [comment]
> > 您好，我想求一份三个模态的各自训练好的文件。 ![image](https://private-user-images.githubusercontent.com/66191779/331137562-8046cdca-4d77-4661-b039-40871c0792c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTc2OTIsIm5iZiI6MTcyNDY1NzM5MiwicGF0aCI6Ii82NjE5MTc3OS8zMzExMzc1NjItODA0NmNkY2EtNGQ3Ny00NjYxLWIwMzktNDA4NzFjMDc5MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3Mjk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYzliOTI2YzZhOTFjM2E2Y2I1MjE3OWYwNzc3OWI5ZmNmZDZiNWNlMThmYjE0MmIzNGQzMTBhMTIwZGFjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U-6P0SJOzSGg1r19d_kOSqDDuSL6AEA88IaVJAXGWr0)
> 
> 您好，请问这个问题怎么解决呢

我这边因为数据搬迁等原因，只保留了训练好的模型（包含多模态训练后的各个模态的encoder），原始的训练好的encoder找不到了。

从其他author那里找回了MOSEI的encoder，已经放在了Google Drive里的 [MOSEI_Encoder_CKPT](https://drive.google.com/drive/folders/1n8MmnRBmlMaWxYP8lAteERqo6OKkuwNI?usp=drive_link) 文件夹下。
其他的两个数据集可以参照代码中config的设定重新微调对应的模型得到近似的结果。

**Comment by XpastaX** [comment]
> > > 您好，我想求一份三个模态的各自训练好的文件。 ![image](https://private-user-images.githubusercontent.com/66191779/331137562-8046cdca-4d77-4661-b039-40871c0792c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzU5NjYsIm5iZiI6MTcxNjE3NTY2NiwicGF0aCI6Ii82NjE5MTc3OS8zMzExMzc1NjItODA0NmNkY2EtNGQ3Ny00NjYxLWIwMzktNDA4NzFjMDc5MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAzMjc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZDNlNTg2ZjljNGQ0MGJiMmRkY2VmNjg0MzMyMjkyYzRmMDMzZTZiZWM1NjgwZDJiMjNkMDRlOTkyNDcxZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D7xzKAkuO8xtdRZdxPylBlEpn5TABN3428P4sti4a9g)
> > 
> > 
> > Hi, 我们的服务器清理过一次，目前只留下了最终的模型文件。如果要做项目的话，可以考虑直接加载最终模型，然后使用encoder作为项目使用，经过多模态训练的encoder效果应该会更好。原始的encoder我这边再找一下，看看能不能找到。
> 
> 您好 我也相求一份三模态各自训练好的文件

目前找回了MOSEI的encoder
