### ISSUE TITLE
关于cls和mean这一部分

### ISSUE THREAD

**Issue by duanruixia** [XpastaX/ConFEDE#19]
刚看完您的论文，对其中关于语音、视频和文本编码后，输入到linear layer之前怎么进行了取CLS以及mean操作，代码中似乎并没有体现，这是为什么呢，因为我理解的是cls和mean是要取三个模态的全局表示，如果我想要三个模态的局部特征表示该怎么做呢

**Comment by XpastaX** [comment]
具体的取mean或者CLS的过程需要到对应模态的encoder中寻找，例如：
https://github.com/XpastaX/ConFEDE/blob/640d8831b6c8befe2a438fe59671caee25ec4edd/SIMS/model/net/constrastive/vision_encoder_finetune.py#L116C28-L116C48

至于局部特征，论文中使用的三个数据集都是提供的提取好的三个模态的 unaligned data。 如果需要提取局部信息，可能需要使用对应数据集提供的aligned的data，然后在训练好encoder 和 ConFEDE后，使用对应token的embedding来提取三个模态的局部信息。

**Comment by duanruixia** [comment]
感谢您的解答，对应模态token的embedding可以在对应模态的encoder中获取吗，我看到
if device is None:
            device = self.device

        x = self.tokenizer(text, padding=True, truncation=True, max_length=256, return_tensors="pt").to(
            device)
        x = self.extractor(**x)['pooler_output']
        if self.with_projector:
            x = self.projector(x)
        return x
 在encoder中返回的是经过池化和投影后的模态的全局表示，那么在这段代码中可以增加返回模态的局部表示吗

**Comment by XpastaX** [comment]
> 感谢您的解答，对应模态token的embedding可以在对应模态的encoder中获取吗，我看到 if device is None: device = self.device
> 
> ```
>     x = self.tokenizer(text, padding=True, truncation=True, max_length=256, return_tensors="pt").to(
>         device)
>     x = self.extractor(**x)['pooler_output']
>     if self.with_projector:
>         x = self.projector(x)
>     return x
> ```
> 
> 在encoder中返回的是经过池化和投影后的模态的全局表示，那么在这段代码中可以增加返回模态的局部表示吗

 需要在对应模态的encoder中增加function实现。比如增加
···
def function1(self, input):
    xxxxxxxx
    return [token embeddings]
···
或者直接修改forward方程，并修改training过程中对应数据传递
