### ISSUE TITLE
FeatureProjector

### ISSUE THREAD

**Issue by ultramarineX** [XpastaX/ConFEDE#4]
为什么Bert编码得到的文本特征要通过一个FeatureProjector，论文中貌似并没有提到

**Comment by XpastaX** [comment]
BERT的输出是768维。开发时加一个projector可以方便与其他模态的embedding维度对齐，随时调节维度大小，方便对比学习。
后面不需要这个功能了，但是没有在代码中剔除这一部分。
https://github.com/XpastaX/ConFEDE/blob/8cd210c692c30d5fc48d84d8572cf52bb6d3786c/SIMS/model/net/constrastive/TVA_fusion.py#L35
https://github.com/XpastaX/ConFEDE/blob/8cd210c692c30d5fc48d84d8572cf52bb6d3786c/SIMS/model/net/constrastive/text_encoder_finetune.py#L62
后续在创建模型的时候，这个功能被set为False

**Comment by ultramarineX** [comment]
谢谢您的解答！
