### ISSUE TITLE
问问

### ISSUE THREAD

**Issue by hyfyxx** [XpastaX/ConFEDE#5]
我用的cuda11.8跑的程序，感觉和本来的环境差距挺大的，最后在CH-SIMS上跑的结果和论文上的有不少差距，
<img width="567" alt="image" src="https://github.com/XpastaX/ConFEDE/assets/128167337/7adb262e-7574-45b6-83b8-9920b259ee98">

**Comment by XpastaX** [comment]
有对text encoder，audio encoder和 vision encoder做训练吗？原本方法需要先对三个encoder模型做训练， 然后再做多模态微调。这个差的有点多，好像没有单独训练encoder。

**Comment by hyfyxx** [comment]
> 有对文本编码器，audio encoder和 vision encoder做训练吗？原本方法需要先对三个编码器模型做训练， 然后再做多模态微调。这个差的有点多，好像没有单独训练编码器。

你好，我有训练哦，但是我的环境与你不大一样，由于系统原因，无法安装低版本的cuda，所以凑巧有一套环境能运行

**Comment by XpastaX** [comment]
> > 有对文本编码器，audio encoder和 vision encoder做训练吗？原本方法需要先对三个编码器模型做训练， 然后再做多模态微调。这个差的有点多，好像没有单独训练编码器。
> 
> 你好，我有训练哦，但是我的环境与你不大一样，由于系统原因，无法安装低版本的cuda，所以凑巧有一套环境能运行

感觉像是没有收敛。因为“Plain” baseline 的表现都要比这个好。需要的话，我可以找找有没有存checkpoint，找到的话可以发给你直接使用。

**Comment by PowerLittleYin** [comment]
你好，请问你最后能复现出论文中的实验结果吗？
