### ISSUE TITLE
预训练的目的

### ISSUE THREAD

**Issue by Wishforpeace** [XpastaX/ConFEDE#6]
您好，请问我在使用文本、图像、音频的预训练后，训练融合网络，结果相差较大，这个结果是否是使用融合网络预训练的结果，先使用单模态预训练和直接训练的区别主要体现在哪里

![2063905428](https://github.com/XpastaX/ConFEDE/assets/90396662/6a1869bf-b507-42e4-b25b-9203c7227902)

**Comment by YJL1004** [comment]
我想问下，这个问题解决了么

**Comment by Wishforpeace** [comment]
> 我想问下，这个问题解决了么

并没有解决，可能跟自身seed设置也有关系

**Comment by XpastaX** [comment]
先使用单模态训练主要是为了让encoder适应对应模态的特征分布，同时通过单模态的准确率确认encoder是否训练成功。绕过单模态训练直接做融合训练的话，模型有几率不稳定，encoder可能无法正确拟合对应模态的特征，而且可能造成BERT的灾难性遗忘。

**Comment by XpastaX** [comment]
> 您好，请问我在使用文本、图像、音频的预训练后，训练融合网络，结果相差较大，这个结果是否是使用融合网络预训练的结果，先使用单模态预训练和直接训练的区别主要体现在哪里
> 
> ![2063905428](https://private-user-images.githubusercontent.com/90396662/313874057-6a1869bf-b507-42e4-b25b-9203c7227902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQzNzAsIm5iZiI6MTcxMzQyNDA3MCwicGF0aCI6Ii85MDM5NjY2Mi8zMTM4NzQwNTctNmExODY5YmYtYjUwNy00MmU0LWIyNWItOTIwM2M3MjI3OTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOWI3ODIwMWY4Nzc5Mzc5NGMyNGM4NzJiZjI2ZGYxOTdlNzRiZTk0OGU5NzZmMzllYTJmZGJkYjk3NDM0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLTiBGfsM0PSmoNcv795VBA0HEQd6oFcELxXhHdQbpw)

目前结果和论文中相差有点大。我这边会看看能不能还找之前的ckpt文件，方便复现。需要一些时间。

**Comment by XpastaX** [comment]
> > 您好，请问我在使用文本、图像、音频的预训练后，训练融合网络，结果相差较大，这个结果是否是使用融合网络预训练的结果，先使用单模态预训练和直接训练的区别主要体现在哪里
> > ![2063905428](https://private-user-images.githubusercontent.com/90396662/313874057-6a1869bf-b507-42e4-b25b-9203c7227902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjQzNzAsIm5iZiI6MTcxMzQyNDA3MCwicGF0aCI6Ii85MDM5NjY2Mi8zMTM4NzQwNTctNmExODY5YmYtYjUwNy00MmU0LWIyNWItOTIwM2M3MjI3OTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA3MDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOWI3ODIwMWY4Nzc5Mzc5NGMyNGM4NzJiZjI2ZGYxOTdlNzRiZTk0OGU5NzZmMzllYTJmZGJkYjk3NDM0YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QLTiBGfsM0PSmoNcv795VBA0HEQd6oFcELxXhHdQbpw)
> 
> 目前结果和论文中相差有点大。我这边会看看能不能还找之前的ckpt文件，方便复现。需要一些时间。

已上传到Google Drive
